In [1]:
import pandas as pd
import numpy as np

ratings = pd.read_csv('tmdb_5000_credits.csv')
ratings.columns

Index(['movie_id', 'title', 'cast', 'crew'], dtype='object')

In [2]:
movies = pd.read_csv('tmdb_5000_movies.csv')

ratings = pd.merge(movies,ratings)
ratings.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count', 'movie_id', 'cast', 'crew'],
      dtype='object')

In [3]:
ratings.drop({'movie_id','budget','genres','homepage','keywords',
              'original_language','original_title','overview','popularity',
              'production_companies','production_countries','release_date','revenue','runtime',
              'spoken_languages','status','tagline','vote_count','cast','crew'},axis=1,inplace=True)
ratings

          id                                     title  vote_average
0      19995                                    Avatar           7.2
1        285  Pirates of the Caribbean: At World's End           6.9
2     206647                                   Spectre           6.3
3      49026                     The Dark Knight Rises           7.6
4      49529                               John Carter           6.1
...      ...                                       ...           ...
4804    9367                               El Mariachi           6.6
4805   72766                                 Newlyweds           5.9
4806  231617                 Signed, Sealed, Delivered           7.0
4807  126186                          Shanghai Calling           5.7
4808   25975                         My Date with Drew           6.3

[4809 rows x 3 columns]

In [4]:
user_ratings = ratings.pivot_table(index=['id'],columns=['title'],values='vote_average')
user_ratings

title,#Horror,(500) Days of Summer,10 Cloverfield Lane,10 Days in a Madhouse,10 Things I Hate About You,102 Dalmatians,10th & Wolf,11:14,12 Angry Men,12 Rounds,...,Zoolander,Zoolander 2,Zoom,Zulu,[REC],[REC]²,eXistenZ,xXx,xXx: State of the Union,Æon Flux
id,,,,,,,,,,,,,,,,,,,,,
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
426067,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
426469,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
433715,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
447027,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
459488,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
user_ratings = user_ratings.fillna(0)
user_ratings

title,#Horror,(500) Days of Summer,10 Cloverfield Lane,10 Days in a Madhouse,10 Things I Hate About You,102 Dalmatians,10th & Wolf,11:14,12 Angry Men,12 Rounds,...,Zoolander,Zoolander 2,Zoom,Zulu,[REC],[REC]²,eXistenZ,xXx,xXx: State of the Union,Æon Flux
id,,,,,,,,,,,,,,,,,,,,,
5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
426067,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
426469,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
433715,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
447027,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
459488,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [6]:
item_similarity_df = user_ratings.corr(method='pearson')
item_similarity_df.head(100)

title,#Horror,(500) Days of Summer,10 Cloverfield Lane,10 Days in a Madhouse,10 Things I Hate About You,102 Dalmatians,10th & Wolf,11:14,12 Angry Men,12 Rounds,...,Zoolander,Zoolander 2,Zoom,Zulu,[REC],[REC]²,eXistenZ,xXx,xXx: State of the Union,Æon Flux
title,,,,,,,,,,,,,,,,,,,,,
#Horror,1.000000,-0.000208,-0.000208,-0.000208,-0.000208,-0.000208,-0.000208,-0.000208,-0.000208,-0.000208,...,-0.000208,-0.000208,-0.000208,-0.000208,-0.000208,-0.000208,-0.000208,-0.000208,-0.000208,-0.000208
(500) Days of Summer,-0.000208,1.000000,-0.000208,-0.000208,-0.000208,-0.000208,-0.000208,-0.000208,-0.000208,-0.000208,...,-0.000208,-0.000208,-0.000208,-0.000208,-0.000208,-0.000208,-0.000208,-0.000208,-0.000208,-0.000208
10 Cloverfield Lane,-0.000208,-0.000208,1.000000,-0.000208,-0.000208,-0.000208,-0.000208,-0.000208,-0.000208,-0.000208,...,-0.000208,-0.000208,-0.000208,-0.000208,-0.000208,-0.000208,-0.000208,-0.000208,-0.000208,-0.000208
10 Days in a Madhouse,-0.000208,-0.000208,-0.000208,1.000000,-0.000208,-0.000208,-0.000208,-0.000208,-0.000208,-0.000208,...,-0.000208,-0.000208,-0.000208,-0.000208,-0.000208,-0.000208,-0.000208,-0.000208,-0.000208,-0.000208
10 Things I Hate About You,-0.000208,-0.000208,-0.000208,-0.000208,1.000000,-0.000208,-0.000208,-0.000208,-0.000208,-0.000208,...,-0.000208,-0.000208,-0.000208,-0.000208,-0.000208,-0.000208,-0.000208,-0.000208,-0.000208,-0.000208
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
A Good Day to Die Hard,-0.000208,-0.000208,-0.000208,-0.000208,-0.000208,-0.000208,-0.000208,-0.000208,-0.000208,-0.000208,...,-0.000208,-0.000208,-0.000208,-0.000208,-0.000208,-0.000208,-0.000208,-0.000208,-0.000208,-0.000208
A Good Year,-0.000208,-0.000208,-0.000208,-0.000208,-0.000208,-0.000208,-0.000208,-0.000208,-0.000208,-0.000208,...,-0.000208,-0.000208,-0.000208,-0.000208,-0.000208,-0.000208,-0.000208,-0.000208,-0.000208,-0.000208
A Guy Named Joe,-0.000208,-0.000208,-0.000208,-0.000208,-0.000208,-0.000208,-0.000208,-0.000208,-0.000208,-0.000208,...,-0.000208,-0.000208,-0.000208,-0.000208,-0.000208,-0.000208,-0.000208,-0.000208,-0.000208,-0.000208
A Guy Thing,-0.000208,-0.000208,-0.000208,-0.000208,-0.000208,-0.000208,-0.000208,-0.000208,-0.000208,-0.000208,...,-0.000208,-0.000208,-0.000208,-0.000208,-0.000208,-0.000208,-0.000208,-0.000208,-0.000208,-0.000208
A Hard Day's Night,-0.000208,-0.000208,-0.000208,-0.000208,-0.000208,-0.000208,-0.000208,-0.000208,-0.000208,-0.000208,...,-0.000208,-0.000208,-0.000208,-0.000208,-0.000208,-0.000208,-0.000208,-0.000208,-0.000208,-0.000208

In [7]:
def get_similar_movies(movie_name,user_rating):
    similar_score = item_similarity_df[movie_name]*(user_rating-5)
    similar_score = similar_score.sort_values(ascending=False)

    return similar_score

In [8]:
#TestData
import random as rand


li = list()
for j in range(1,100000):
    ni=rand.randint(1,10)
    rand_user = set()
    for i in range(ni):
        user1 = ratings.sample(axis='index')
        user1 = user1.title
        rate = rand.randint(0,10)
        user1 = user1.values
        rand_user.add((user1[0],rate))
    li.append(rand_user)

li.__len__()

99999

In [9]:
import pickle
pickle.dump(li,open('listofusers.pkl','wb'))

In [57]:
similar_movies = pd.DataFrame()

val = int(input("Enter the userid(0-100000):"))
rand_user = li[val]
for movie,rating in rand_user:
    similar_movies = similar_movies.append(get_similar_movies(movie,rating),ignore_index=True)

similar_movies.head()
z=similar_movies.sum().sort_values(ascending=False)

z=z.to_frame()
z=z.drop(columns=0)
pickle.dump(z.head(5),open('results.pkl','wb'))
z

C:\Users\prajw\AppData\Local\Temp\ipykernel_7784\1628734554.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  similar_movies = similar_movies.append(get_similar_movies(movie,rating),ignore_index=True)
C:\Users\prajw\AppData\Local\Temp\ipykernel_7784\1628734554.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  similar_movies = similar_movies.append(get_similar_movies(movie,rating),ignore_index=True)
C:\Users\prajw\AppData\Local\Temp\ipykernel_7784\1628734554.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  similar_movies = similar_movies.append(get_similar_movies(movie,rating),ignore_index=True)
C:\Users\prajw\AppData\Local\Temp\ipykernel_7784\1628734554.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  similar_movies = similar_movies.append(get_similar_movies(movie,rating),ignore_index=True)

Empty DataFrame
Columns: []
Index: [The Best of Me, Pink Flamingos, The Living Daylights, War of the Worlds, The Lost World: Jurassic Park, The Day After Tomorrow, Star Trek: The Motion Picture, The Interpreter, Octopussy, Bend It Like Beckham, The Crime of Padre Amaro, Cinderella Man, 2 Fast 2 Furious, Quarantine, Race to Witch Mountain, Slow Burn, The Perfect Man, Woman on Top, Lone Wolf McQuade, Hoot, The Cry of the Owl, A Simple Wish, Simply Irresistible, Gremlins 2: The New Batch, Gossip, The Dark Hours, Duets, Double Take, Trust the Man, Underclassman, Austin Powers: The Spy Who Shagged Me, Life as a House, From Here to Eternity, The Brown Bunny, Frost/Nixon, Beastmaster 2: Through the Portal of Time, Pat Garrett & Billy the Kid, Toy Story 2, Win a Date with Tad Hamilton!, The Lord of the Rings: The Return of the King, The Bridges of Madison County, The Emperor's New Groove, Joyeux Noël, White Oleander, Samantha: An American Girl Holiday, Apollo 13, Undercover Brother, Blazing Saddles, Bride of Chucky, Swingers, Joe Somebody, Escape from Alcatraz, I Am Sam, Match Point, The Sweet Hereafter, Star Trek II: The Wrath of Khan, Army of Darkness, Jackie Brown, Deuces Wild, Inside Man, O Brother, Where Art Thou?, Lost in Translation, Pocketful of Miracles, Dead Man Walking, Megiddo: The Omega Code 2, Predator, The Texas Chain Saw Massacre, Vanity Fair, Stripes, America's Sweethearts, Jeepers Creepers 2, Walk the Line, The Evil Dead, Guess Who, The Last Samurai, The Pallbearer, The Fifth Element, Much Ado About Nothing, The Terminator, Thomas and the Magic Railroad, Volver, Hard Rain, Dragon Hunters, Inspector Gadget, Hellboy II: The Golden Army, Abandon, Flight of the Intruder, Not Another Teen Movie, The Lizzie McGuire Movie, Morvern Callar, Law Abiding Citizen, Nowhere Boy, Glitter, Love Jones, Scott Pilgrim vs. the World, Martian Child, Being John Malkovich, Inception, The Hangover, The Legend of Drunken Master, ...]

[4800 rows x 0 columns]